- hosts: localhost
  vars:
    namespace: vpn
    src_dir: "{{lookup('ansible.builtin.env', 'HOME')}}/src/{{namespace}}"
    dependencies: [
      "JupyterNotebook.ide",
      "WebScraper.AI",
      "VPN.index",
    ]
  tasks:
  - name: Pre playbook
    ansible.builtin.shell: ansible-playbook pre.yml
    args:
      chdir: "{{ src_dir }}/{{ item }}/src/ansible"
      creates: "{{ src_dir }}/{{ item }}/src/ansible/.pre/.depends/git"
    loop: "{{ dependencies }}"
