- hosts: localhost
  vars:
    src: ""
    uni: ".uni/"
    vpn: "vpn/"
    bitgraph: "{{uni}}/bitgraph/"
    repo: [
      { subdir: "{{bitgraph}}", repo: "git@github.com:BitGraph/MariaDB.git", name: "MariaDB"},
      { subdir: "{{vpn}}", repo: "git@github.com:UnicornVPN/VPN.index.git", name: "VPN.index"},
      { subdir: "{{vpn}}", repo: "git@github.com:Source-Graph/JupyterNotebook.ide.git", name: "JupyterNotebook.ide"},
      { subdir: "{{vpn}}", repo: "git@github.com:Uni-AI/WebScraper.AI.git", name: "WebScraper.AI"},
      ]

  tasks:
  - debug:
      msg: "{{item.name}}"
    loop: "{{repo}}"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{item.repo}}"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/{{item.subdir}}{{item.name}}"
    loop: "{{repo}}"
